services:
  postgres:
    image: 'postgres:latest'
    container_name: 'notify'
    environment:
      - 'POSTGRES_DB=notify'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
      - 'PGDATA=/var/lib/postgresql/data'
    ports:
      - '5437:5432'
